version: '2.0'
services:
  redis:
    image: redis:alpine
    container_name: pimcore-redis

  db:
    image: mariadb:10.4
    container_name: pimcore-mariadb
    working_dir: /application
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-format=Barracuda, --innodb-large-prefix=1, --innodb-file-per-table=1]
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
      - MYSQL_DATABASE=pimcore
      - MYSQL_USER=pimcore
      - MYSQL_PASSWORD=pimcore

  php:
    image: pimcore/pimcore:PHP8.0-apache
    container_name: pimcore-php
    volumes:
      - .:/pimcore-field-translator-bundle
      - ~/.composer:/tmp/composer:delegated
    ports:
      - "2000:80"
      - "2001:443"
    links:
      - db:db
      - redis:redis
    environment:
      - COMPOSER_HOME=/tmp/composer
      - COMPOSER_MEMORY_LIMIT=-1


volumes:
  pimcore-database:
