services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Basilicom\FieldTranslatorBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Basilicom\FieldTranslatorBundle\Controller\DefaultController:
        arguments: ['@Basilicom\FieldTranslatorBundle\Translator\Translator']

    Basilicom\FieldTranslatorBundle\Translator\TranslatorFactory: ~

    Basilicom\FieldTranslatorBundle\Translator\Translator:
        # the first argument is the class and the second argument is the static method
        factory: ['@Basilicom\FieldTranslatorBundle\Translator\TranslatorFactory', 'createTranslator']
